version: '3.8'

services:
  app:
    # build:
    #   context: .
    #   dockerfile: ./.docker/Dockerfile
    image: redtius/laravel-example:latest
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: Laravel-Sample-App
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: wordb
      DB_USERNAME: laravel
      DB_PASSWORD: reda
    depends_on:
      - db
    networks:
      - laravel_network
    command: /usr/local/bin/Entrypoint.sh

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: wordb
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: reda
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge
